import React from 'react';
import Adapter from '@wojtekmaj/enzyme-adapter-react-17';
import { fireEvent, screen } from '@testing-library/jest-dom';
import { act } from '@testing-library/react';
import Enzyme, { shallow, configure, mount, sel } from 'enzyme';
import configureMockStore from 'redux-mock-store';
import { provider } from 'react-redux';
Enzyme.configure({ adapter: new Adapter() });
import ShallowMock from 'src/content/SuperAdmin/EditUser/shallow';
import * as reactRedux from 'react-redux';
import { unmountComponentAtNode } from 'react-dom';
import thunk from 'redux-thunk';
import { useLocation } from 'react-router';
import { Router } from 'react-router';
import * as router from 'react-router';

import clsx from 'clsx';
import OrderHistory from '../orderHistory';
const mockStore = configureMockStore([thunk]);

jest.mock('react-redux', () => ({
    connect: () => jest.fn(),
    useSelector: jest.fn((fn) => fn()),
    useDispatch: () => jest.fn(),
    useEffect: jest.fn()
}));

const mockedUsedNavigate = jest.fn();
jest.mock('react-router-dom', () => ({
    ...jest.requireActual('react-router-dom'),
    useNavigate: () => mockedUsedNavigate,
    Link: (props) => {
        return <a {...props} href={props.to} />;
      },
    useEffect: () => mockedUsedNavigate,
    useLocation: () => ({
        pathname: '/',
        search: '',
        type: ''
    })
}));


describe('EditUser', () => {
    let wrapper;

    const store = mockStore({
        customerPortal: {
            getCustomerOrderHistory: {
              content: [
                {
                  id: null,
                  partNumber: 'T403338',
                  customerNumber: 46030,
                  orderNumber: '01012396',
                  salesOrderId: '1144656',
                  salesOrderNumber: '01012396',
                  customerOrderNumber: '5501169084',
                  partDescription: 'VAP',
                  uom: 'EA',
                  actualUom: 'EA',
                  quantity: 20,
                  actualQuantity: 20,
                  invoiceDate: '2022-01-27',
                  invoiceFilePath: '/I000045286.pdf',
                  packingListFilePath: '/CUSTOMER/PK/2022/01/PK01125730.pdf',
                  podFilePath: '',
                  mtrFilePath: '/MTR202107/8800376287.pdf',
                  updatedBy: null
                },
                {
                  id: null,
                  partNumber: 'T448604',
                  customerNumber: 46030,
                  orderNumber: '01012383',
                  salesOrderId: '1144647',
                  salesOrderNumber: '01012383',
                  customerOrderNumber: '5501293392',
                  partDescription: 'VAP JD T44 8604 VAP',
                  uom: 'EA',
                  actualUom: 'EA',
                  quantity: 2,
                  actualQuantity: 2,
                  invoiceDate: '2022-01-27',
                  invoiceFilePath: '/I000045277.pdf',
                  packingListFilePath: '/CUSTOMER/PK/2022/01/PK01125534.pdf',
                  podFilePath: '',
                  mtrFilePath: '/MTR202110/8800383268.pdf',
                  updatedBy: null
                },
                {
                  id: null,
                  partNumber: 'T411067',
                  customerNumber: 46030,
                  orderNumber: '01012385',
                  salesOrderId: '1144649',
                  salesOrderNumber: '01012385',
                  customerOrderNumber: '5501027223',
                  partDescription: 'VAP',
                  uom: 'EA',
                  actualUom: 'EA',
                  quantity: 60,
                  actualQuantity: 60,
                  invoiceDate: '2022-01-27',
                  invoiceFilePath: '/I000045279.pdf',
                  packingListFilePath: '/CUSTOMER/PK/2022/01/PK01125550.pdf',
                  podFilePath: '',
                  mtrFilePath: '/MTR202110/8800383269.pdf',
                  updatedBy: null
                },
                {
                  id: null,
                  partNumber: 'T411008',
                  customerNumber: 46030,
                  orderNumber: '01012384',
                  salesOrderId: '1144648',
                  salesOrderNumber: '01012384',
                  customerOrderNumber: '5501027222',
                  partDescription: 'VAP',
                  uom: 'EA',
                  actualUom: 'EA',
                  quantity: 29,
                  actualQuantity: 29,
                  invoiceDate: '2022-01-27',
                  invoiceFilePath: '/I000045278.pdf',
                  packingListFilePath: '/CUSTOMER/PK/2022/01/PK01125548.pdf',
                  podFilePath: '',
                  mtrFilePath: '/MTR202109/8800380765.pdf',
                  updatedBy: null
                },
                {
                  id: null,
                  partNumber: 'W58708',
                  customerNumber: 46030,
                  orderNumber: '01012372',
                  salesOrderId: '1144259',
                  salesOrderNumber: '01012372',
                  customerOrderNumber: '5500937218',
                  partDescription: 'PIPE VAP',
                  uom: 'EA',
                  actualUom: 'EA',
                  quantity: 15,
                  actualQuantity: 15,
                  invoiceDate: '2022-01-25',
                  invoiceFilePath: '/I000045254.pdf',
                  packingListFilePath: '/CUSTOMER/PK/2022/01/PK01124461.pdf',
                  podFilePath: '',
                  mtrFilePath: '/MTR202110/8800382695.pdf',
                  updatedBy: null
                },
                {
                  id: null,
                  partNumber: 'A97957',
                  customerNumber: 46030,
                  orderNumber: '01011634',
                  salesOrderId: '1143822',
                  salesOrderNumber: '01011634',
                  customerOrderNumber: '5500785002',
                  partDescription: 'VAP',
                  uom: 'EA',
                  actualUom: 'EA',
                  quantity: 77,
                  actualQuantity: 77,
                  invoiceDate: '2022-01-25',
                  invoiceFilePath: '/I000045231.pdf',
                  packingListFilePath: '/CUSTOMER/PK/2021/12/PK01099803.pdf',
                  podFilePath: '',
                  mtrFilePath: '',
                  updatedBy: null
                },
                {
                  id: null,
                  partNumber: 'A87905',
                  customerNumber: 46030,
                  orderNumber: '01012234',
                  salesOrderId: '1143833',
                  salesOrderNumber: '01012234',
                  customerOrderNumber: '5500839921',
                  partDescription: 'VAP',
                  uom: 'EA',
                  actualUom: 'EA',
                  quantity: 24,
                  actualQuantity: 24,
                  invoiceDate: '2022-01-25',
                  invoiceFilePath: '/I000045242.pdf',
                  packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120374.pdf',
                  podFilePath: '',
                  mtrFilePath: '/MTR202201/8800388413.pdf',
                  updatedBy: null
                },
                {
                  id: null,
                  partNumber: 'W52352',
                  customerNumber: 46030,
                  orderNumber: '01012347',
                  salesOrderId: '1143824',
                  salesOrderNumber: '01012347',
                  customerOrderNumber: '5500784985',
                  partDescription: 'VAP',
                  uom: 'EA',
                  actualUom: 'EA',
                  quantity: 672,
                  actualQuantity: 672,
                  invoiceDate: '2022-01-25',
                  invoiceFilePath: '/I000045233.pdf',
                  packingListFilePath: '/CUSTOMER/PK/2022/01/PK01123713.pdf',
                  podFilePath: '',
                  mtrFilePath: '/MTR202110/8800381330.pdf',
                  updatedBy: null
                },
                {
                  id: null,
                  partNumber: 'PXX10286',
                  customerNumber: 46030,
                  orderNumber: '01012368',
                  salesOrderId: '1144255',
                  salesOrderNumber: '01012368',
                  customerOrderNumber: '5500928211',
                  partDescription: 'VAP',
                  uom: 'EA',
                  actualUom: 'EA',
                  quantity: 80,
                  actualQuantity: 80,
                  invoiceDate: '2022-01-25',
                  invoiceFilePath: '/I000045250.pdf',
                  packingListFilePath: '/CUSTOMER/PK/2022/01/PK01124441.pdf',
                  podFilePath: '',
                  mtrFilePath: '/MTR202110/8800383599.pdf',
                  updatedBy: null
                },
                {
                  id: null,
                  partNumber: 'W60094',
                  customerNumber: 46030,
                  orderNumber: '01012373',
                  salesOrderId: '1144260',
                  salesOrderNumber: '01012373',
                  customerOrderNumber: '5500832081',
                  partDescription: 'VAP',
                  uom: 'EA',
                  actualUom: 'EA',
                  quantity: 44,
                  actualQuantity: 44,
                  invoiceDate: '2022-01-25',
                  invoiceFilePath: '/I000045255.pdf',
                  packingListFilePath: '/CUSTOMER/PK/2022/01/PK01124465.pdf',
                  podFilePath: '',
                  mtrFilePath: '/MTR202108/8800379215.pdf',
                  updatedBy: null
                }
              ],
              pageable: {
                sort: {
                  sorted: true,
                  unsorted: false,
                  empty: false
                },
                pageNumber: 0,
                pageSize: 10,
                offset: 0,
                paged: true,
                unpaged: false
              },
              last: false,
              totalElements: 63,
              totalPages: 7,
              first: true,
              sort: {
                sorted: true,
                unsorted: false,
                empty: false
              },
              numberOfElements: 10,
              size: 10,
              number: 0,
              empty: false
            },
            
                getCustomerOrderExcel: {
                  content: [
                    {
                      id: null,
                      partNumber: 'T411008',
                      customerNumber: 46030,
                      orderNumber: '01012384',
                      salesOrderId: '1144648',
                      salesOrderNumber: '01012384',
                      customerOrderNumber: '5501027222',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 29,
                      actualQuantity: 29,
                      invoiceDate: '2022-01-27',
                      invoiceFilePath: '/I000045278.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01125548.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800380765.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T403338',
                      customerNumber: 46030,
                      orderNumber: '01012396',
                      salesOrderId: '1144656',
                      salesOrderNumber: '01012396',
                      customerOrderNumber: '5501169084',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 20,
                      actualQuantity: 20,
                      invoiceDate: '2022-01-27',
                      invoiceFilePath: '/I000045286.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01125730.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202107/8800376287.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T448604',
                      customerNumber: 46030,
                      orderNumber: '01012383',
                      salesOrderId: '1144647',
                      salesOrderNumber: '01012383',
                      customerOrderNumber: '5501293392',
                      partDescription: 'VAP JD T44 8604 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 2,
                      actualQuantity: 2,
                      invoiceDate: '2022-01-27',
                      invoiceFilePath: '/I000045277.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01125534.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800383268.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T411067',
                      customerNumber: 46030,
                      orderNumber: '01012385',
                      salesOrderId: '1144649',
                      salesOrderNumber: '01012385',
                      customerOrderNumber: '5501027223',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 60,
                      actualQuantity: 60,
                      invoiceDate: '2022-01-27',
                      invoiceFilePath: '/I000045279.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01125550.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800383269.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W51197',
                      customerNumber: 46030,
                      orderNumber: '01012371',
                      salesOrderId: '1144257',
                      salesOrderNumber: '01012371',
                      customerOrderNumber: '5500790310',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 120,
                      actualQuantity: 120,
                      invoiceDate: '2022-01-25',
                      invoiceFilePath: '/I000045252.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01124451.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800380998.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'PXX12963',
                      customerNumber: 46030,
                      orderNumber: '01012369',
                      salesOrderId: '1144256',
                      salesOrderNumber: '01012369',
                      customerOrderNumber: '5501314441',
                      partDescription: 'CRS 8.625X0.500 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 36,
                      actualQuantity: 36,
                      invoiceDate: '2022-01-25',
                      invoiceFilePath: '/I000045251.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01124447.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800383761.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W58708',
                      customerNumber: 46030,
                      orderNumber: '01012372',
                      salesOrderId: '1144259',
                      salesOrderNumber: '01012372',
                      customerOrderNumber: '5500937218',
                      partDescription: 'PIPE VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 15,
                      actualQuantity: 15,
                      invoiceDate: '2022-01-25',
                      invoiceFilePath: '/I000045254.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01124461.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800382695.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'A97957',
                      customerNumber: 46030,
                      orderNumber: '01011634',
                      salesOrderId: '1143822',
                      salesOrderNumber: '01011634',
                      customerOrderNumber: '5500785002',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 77,
                      actualQuantity: 77,
                      invoiceDate: '2022-01-25',
                      invoiceFilePath: '/I000045231.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2021/12/PK01099803.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'A87905',
                      customerNumber: 46030,
                      orderNumber: '01012234',
                      salesOrderId: '1143833',
                      salesOrderNumber: '01012234',
                      customerOrderNumber: '5500839921',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 24,
                      actualQuantity: 24,
                      invoiceDate: '2022-01-25',
                      invoiceFilePath: '/I000045242.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120374.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202201/8800388413.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W52352',
                      customerNumber: 46030,
                      orderNumber: '01012347',
                      salesOrderId: '1143824',
                      salesOrderNumber: '01012347',
                      customerOrderNumber: '5500784985',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 672,
                      actualQuantity: 672,
                      invoiceDate: '2022-01-25',
                      invoiceFilePath: '/I000045233.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01123713.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800381330.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'PXX10286',
                      customerNumber: 46030,
                      orderNumber: '01012368',
                      salesOrderId: '1144255',
                      salesOrderNumber: '01012368',
                      customerOrderNumber: '5500928211',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 80,
                      actualQuantity: 80,
                      invoiceDate: '2022-01-25',
                      invoiceFilePath: '/I000045250.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01124441.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800383599.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W60094',
                      customerNumber: 46030,
                      orderNumber: '01012373',
                      salesOrderId: '1144260',
                      salesOrderNumber: '01012373',
                      customerOrderNumber: '5500832081',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 44,
                      actualQuantity: 44,
                      invoiceDate: '2022-01-25',
                      invoiceFilePath: '/I000045255.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01124465.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202108/8800379215.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'KK16969',
                      customerNumber: 46030,
                      orderNumber: '01012344',
                      salesOrderId: '1143823',
                      salesOrderNumber: '01012344',
                      customerOrderNumber: '5500919587',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 50,
                      actualQuantity: 50,
                      invoiceDate: '2022-01-25',
                      invoiceFilePath: '/I000045232.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01123700.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800382918.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W50139',
                      customerNumber: 46030,
                      orderNumber: '01012370',
                      salesOrderId: '1144258',
                      salesOrderNumber: '01012370',
                      customerOrderNumber: '5500790050',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 132,
                      actualQuantity: 132,
                      invoiceDate: '2022-01-25',
                      invoiceFilePath: '/I000045253.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01124449.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800380996.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'A91926',
                      customerNumber: 46030,
                      orderNumber: '01012343',
                      salesOrderId: '1143827',
                      salesOrderNumber: '01012343',
                      customerOrderNumber: '5500839926',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 18,
                      actualQuantity: 18,
                      invoiceDate: '2022-01-24',
                      invoiceFilePath: '/I000045236.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01123694.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800382912.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W55698',
                      customerNumber: 46030,
                      orderNumber: '01012350',
                      salesOrderId: '1143832',
                      salesOrderNumber: '01012350',
                      customerOrderNumber: '5500784573',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 65,
                      actualQuantity: 65,
                      invoiceDate: '2022-01-24',
                      invoiceFilePath: '/I000045241.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01123800.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800383917.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '6Y5873 EC05',
                      customerNumber: 45772,
                      orderNumber: '61167444',
                      salesOrderId: '1144466',
                      salesOrderNumber: '61167444',
                      customerOrderNumber: 'TARP86506',
                      partDescription: '3.750 1E0360 32.543 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 139,
                      actualQuantity: 139,
                      invoiceDate: '2022-01-24',
                      invoiceFilePath: '/I002237752.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01122741.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'A91916',
                      customerNumber: 46030,
                      orderNumber: '01011630',
                      salesOrderId: '1143825',
                      salesOrderNumber: '01011630',
                      customerOrderNumber: '5500839922',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 20,
                      actualQuantity: 20,
                      invoiceDate: '2022-01-24',
                      invoiceFilePath: '/I000045234.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2021/12/PK01099737.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'KK18190',
                      customerNumber: 46030,
                      orderNumber: '01012345',
                      salesOrderId: '1143828',
                      salesOrderNumber: '01012345',
                      customerOrderNumber: '5500921978',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 1000,
                      actualQuantity: 1000,
                      invoiceDate: '2022-01-24',
                      invoiceFilePath: '/I000045237.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01123702.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800381718.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W55009',
                      customerNumber: 46030,
                      orderNumber: '01012348',
                      salesOrderId: '1143830',
                      salesOrderNumber: '01012348',
                      customerOrderNumber: '5500784027',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 60,
                      actualQuantity: 60,
                      invoiceDate: '2022-01-24',
                      invoiceFilePath: '/I000045239.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01123788.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202108/8800378638.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'L157244',
                      customerNumber: 46030,
                      orderNumber: '01012346',
                      salesOrderId: '1143829',
                      salesOrderNumber: '01012346',
                      customerOrderNumber: '5500784160',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 851,
                      actualQuantity: 851,
                      invoiceDate: '2022-01-24',
                      invoiceFilePath: '/I000045238.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01123706.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202111/8800384685.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'A91925',
                      customerNumber: 46030,
                      orderNumber: '01012342',
                      salesOrderId: '1143826',
                      salesOrderNumber: '01012342',
                      customerOrderNumber: '5500839925',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 8,
                      actualQuantity: 8,
                      invoiceDate: '2022-01-24',
                      invoiceFilePath: '/I000045235.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01123686.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202107/8800376047.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W55682',
                      customerNumber: 46030,
                      orderNumber: '01012349',
                      salesOrderId: '1143831',
                      salesOrderNumber: '01012349',
                      customerOrderNumber: '5500784983',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 300,
                      actualQuantity: 300,
                      invoiceDate: '2022-01-24',
                      invoiceFilePath: '/I000045240.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01123794.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800382212.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '7S6834-24',
                      customerNumber: 45772,
                      orderNumber: '61167363',
                      salesOrderId: '1143640',
                      salesOrderNumber: '61167363',
                      customerOrderNumber: 'TARP89425',
                      partDescription: '4.25 1E0360 28.622 +.0 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 24,
                      actualQuantity: 24,
                      invoiceDate: '2022-01-21',
                      invoiceFilePath: '/I002237013.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120984.pdf',
                      podFilePath: '/CUSTOMER/MN/2022/01/MN00128194.pdf',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '1287116-03',
                      customerNumber: 45772,
                      orderNumber: '61167361',
                      salesOrderId: '1143639',
                      salesOrderNumber: '61167361',
                      customerOrderNumber: 'TARP94212',
                      partDescription: '4.25 1E0360 22.339 +.0 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 20,
                      actualQuantity: 20,
                      invoiceDate: '2022-01-21',
                      invoiceFilePath: '/I002237014.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120982.pdf',
                      podFilePath: '/CUSTOMER/MN/2022/01/MN00128194.pdf',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W56060',
                      customerNumber: 46030,
                      orderNumber: '01012317',
                      salesOrderId: '1143173',
                      salesOrderNumber: '01012317',
                      customerOrderNumber: '5500790944',
                      partDescription: 'W56060 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 180,
                      actualQuantity: 180,
                      invoiceDate: '2022-01-20',
                      invoiceFilePath: '/I000045194.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01122245.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800381102.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T400624',
                      customerNumber: 46030,
                      orderNumber: '01012277',
                      salesOrderId: '1142768',
                      salesOrderNumber: '01012277',
                      customerOrderNumber: '5501169085',
                      partDescription: 'TUBE VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 20,
                      actualQuantity: 20,
                      invoiceDate: '2022-01-20',
                      invoiceFilePath: '/I000045165.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01121812.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800383712.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'PXX10559',
                      customerNumber: 46030,
                      orderNumber: '01012278',
                      salesOrderId: '1143174',
                      salesOrderNumber: '01012278',
                      customerOrderNumber: '5501012094',
                      partDescription: 'VAP JD PXX10 559 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 20,
                      actualQuantity: 20,
                      invoiceDate: '2022-01-20',
                      invoiceFilePath: '/I000045195.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01121820.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202108/8800380173.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T215708',
                      customerNumber: 46030,
                      orderNumber: '01012276',
                      salesOrderId: '1142767',
                      salesOrderNumber: '01012276',
                      customerOrderNumber: '5500995407',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 20,
                      actualQuantity: 20,
                      invoiceDate: '2022-01-20',
                      invoiceFilePath: '/I000045164.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01121810.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800383711.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'w56060',
                      customerNumber: 46030,
                      orderNumber: '01012317',
                      salesOrderId: '1143173',
                      salesOrderNumber: '01012317',
                      customerOrderNumber: '5500790944',
                      partDescription: 'W56060 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 180,
                      actualQuantity: 180,
                      invoiceDate: '2022-01-20',
                      invoiceFilePath: '/I000045194.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01122245.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800381102.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T411008',
                      customerNumber: 46030,
                      orderNumber: '01012259',
                      salesOrderId: '1142356',
                      salesOrderNumber: '01012259',
                      customerOrderNumber: '5501027222',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 29,
                      actualQuantity: 29,
                      invoiceDate: '2022-01-19',
                      invoiceFilePath: '/I000045129.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01121076.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800380765.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'R551884',
                      customerNumber: 46030,
                      orderNumber: '01012246',
                      salesOrderId: '1142359',
                      salesOrderNumber: '01012246',
                      customerOrderNumber: '5500995034',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 80,
                      actualQuantity: 80,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045132.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120591.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800383047.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '5444188-04',
                      customerNumber: 45772,
                      orderNumber: '61167143',
                      salesOrderId: '1143333',
                      salesOrderNumber: '61167143',
                      customerOrderNumber: 'TARP94083',
                      partDescription: '3.25 1E1054  8.657 +05 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 1249,
                      actualQuantity: 1249,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I002236678.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01117189.pdf',
                      podFilePath: '/CUSTOMER/MN/2022/01/MN00127952.pdf',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'A87905',
                      customerNumber: 46030,
                      orderNumber: '01011629',
                      salesOrderId: '1141967',
                      salesOrderNumber: '01011629',
                      customerOrderNumber: '5500839921',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 66,
                      actualQuantity: 66,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045116.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2021/12/PK01099720.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W52352',
                      customerNumber: 46030,
                      orderNumber: '01012237',
                      salesOrderId: '1141970',
                      salesOrderNumber: '01012237',
                      customerOrderNumber: '',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 1568,
                      actualQuantity: 1568,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045119.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120390.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800380995.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T214195',
                      customerNumber: 46030,
                      orderNumber: '01012247',
                      salesOrderId: '1142360',
                      salesOrderNumber: '01012247',
                      customerOrderNumber: '5500995406',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 32,
                      actualQuantity: 32,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045133.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120593.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800380766.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T448604',
                      customerNumber: 46030,
                      orderNumber: '01012251',
                      salesOrderId: '1142364',
                      salesOrderNumber: '01012251',
                      customerOrderNumber: '5501293392',
                      partDescription: 'VAP JD T44 8604 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 5,
                      actualQuantity: 5,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045137.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120612.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800383268.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '2943365-01',
                      customerNumber: 45772,
                      orderNumber: '61167329',
                      salesOrderId: '1144026',
                      salesOrderNumber: '61167329',
                      customerOrderNumber: 'TARP88131',
                      partDescription: '4.25 1E0360 28.661 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 144,
                      actualQuantity: 144,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I002237371.pdf',
                      packingListFilePath: '',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'w56060',
                      customerNumber: 46030,
                      orderNumber: '01012239',
                      salesOrderId: '1141972',
                      salesOrderNumber: '01012239',
                      customerOrderNumber: '5500790944',
                      partDescription: 'W56060 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 180,
                      actualQuantity: 180,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045121.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120402.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800381102.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '3210905-02',
                      customerNumber: 45772,
                      orderNumber: '61167278',
                      salesOrderId: '1142161',
                      salesOrderNumber: '61167278',
                      customerOrderNumber: 'TARP86503',
                      partDescription: '3.125 1E0360 37.528 +/ VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 136,
                      actualQuantity: 136,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I002235644.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01119926.pdf',
                      podFilePath: '/CUSTOMER/MN/2022/01/MN00127968.pdf',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T411067',
                      customerNumber: 46030,
                      orderNumber: '01012250',
                      salesOrderId: '1142363',
                      salesOrderNumber: '01012250',
                      customerOrderNumber: '5501027223',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 6,
                      actualQuantity: 6,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045136.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120608.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800383269.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W55009',
                      customerNumber: 46030,
                      orderNumber: '01012238',
                      salesOrderId: '1141971',
                      salesOrderNumber: '01012238',
                      customerOrderNumber: '5500784027',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 20,
                      actualQuantity: 20,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045120.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120394.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '1271001-05',
                      customerNumber: 45772,
                      orderNumber: '61167328',
                      salesOrderId: '1143343',
                      salesOrderNumber: '61167328',
                      customerOrderNumber: 'TARP86972',
                      partDescription: '4.25 1E0360 22.791 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 80,
                      actualQuantity: 80,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I002236677.pdf',
                      packingListFilePath: '',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T355332',
                      customerNumber: 46030,
                      orderNumber: '01012248',
                      salesOrderId: '1142361',
                      salesOrderNumber: '01012248',
                      customerOrderNumber: '5501007820',
                      partDescription: 'TUBE TUBE UPPER VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 6,
                      actualQuantity: 6,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045134.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120598.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202112/8800386135.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'R538471',
                      customerNumber: 46030,
                      orderNumber: '01012244',
                      salesOrderId: '1142357',
                      salesOrderNumber: '01012244',
                      customerOrderNumber: '5500995032',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 1080,
                      actualQuantity: 1080,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045130.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120581.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '3210905-02',
                      customerNumber: 45772,
                      orderNumber: '61167279',
                      salesOrderId: '1142554',
                      salesOrderNumber: '61167279',
                      customerOrderNumber: 'TARP86503',
                      partDescription: '3.125 1E0360 37.528 +/ VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 136,
                      actualQuantity: 136,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I002235996.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01119932.pdf',
                      podFilePath: '/CUSTOMER/MN/2022/01/MN00127952.pdf',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'A91917',
                      customerNumber: 46030,
                      orderNumber: '01012235',
                      salesOrderId: '1141968',
                      salesOrderNumber: '01012235',
                      customerOrderNumber: '5500839923',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 2,
                      actualQuantity: 2,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045117.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120378.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800382907.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'R538472',
                      customerNumber: 46030,
                      orderNumber: '01012245',
                      salesOrderId: '1142358',
                      salesOrderNumber: '01012245',
                      customerOrderNumber: '5500995033',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 284,
                      actualQuantity: 284,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045131.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120587.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800382393.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W56060',
                      customerNumber: 46030,
                      orderNumber: '01012239',
                      salesOrderId: '1141972',
                      salesOrderNumber: '01012239',
                      customerOrderNumber: '5500790944',
                      partDescription: 'W56060 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 180,
                      actualQuantity: 180,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045121.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120402.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202109/8800381102.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T389233',
                      customerNumber: 46030,
                      orderNumber: '01012249',
                      salesOrderId: '1142362',
                      salesOrderNumber: '01012249',
                      customerOrderNumber: '5500995408',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 20,
                      actualQuantity: 20,
                      invoiceDate: '2022-01-18',
                      invoiceFilePath: '/I000045135.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120604.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202110/8800384205.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '1070091112',
                      customerNumber: 46030,
                      orderNumber: '01011672',
                      salesOrderId: '1141953',
                      salesOrderNumber: '01011672',
                      customerOrderNumber: '5501000312',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 1,
                      actualQuantity: 1,
                      invoiceDate: '2022-01-17',
                      invoiceFilePath: '/I000045103.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2021/12/PK01100177.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '1080093228',
                      customerNumber: 46030,
                      orderNumber: '01011678',
                      salesOrderId: '1141954',
                      salesOrderNumber: '01011678',
                      customerOrderNumber: '5501000289',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 9,
                      actualQuantity: 9,
                      invoiceDate: '2022-01-17',
                      invoiceFilePath: '/I000045104.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2021/12/PK01100207.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W55801',
                      customerNumber: 46030,
                      orderNumber: '01012228',
                      salesOrderId: '1141652',
                      salesOrderNumber: '01012228',
                      customerOrderNumber: '4512076282',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 629,
                      actualQuantity: 629,
                      invoiceDate: '2022-01-17',
                      invoiceFilePath: '/I000045093.pdf',
                      packingListFilePath: '',
                      podFilePath: '',
                      mtrFilePath: '/MTR202101/8800365026.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'W48161',
                      customerNumber: 46030,
                      orderNumber: '01012233',
                      salesOrderId: '1141956',
                      salesOrderNumber: '01012233',
                      customerOrderNumber: '5500789170',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 648,
                      actualQuantity: 648,
                      invoiceDate: '2022-01-17',
                      invoiceFilePath: '/I000045106.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01120184.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '1070091110',
                      customerNumber: 46030,
                      orderNumber: '01011670',
                      salesOrderId: '1141951',
                      salesOrderNumber: '01011670',
                      customerOrderNumber: '5501000287',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 10,
                      actualQuantity: 10,
                      invoiceDate: '2022-01-17',
                      invoiceFilePath: '/I000045101.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2021/12/PK01100171.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: 'T388547',
                      customerNumber: 46030,
                      orderNumber: '01012229',
                      salesOrderId: '1141656',
                      salesOrderNumber: '01012229',
                      customerOrderNumber: '5500995410',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 10,
                      actualQuantity: 10,
                      invoiceDate: '2022-01-17',
                      invoiceFilePath: '/I000045097.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2022/01/PK01119802.pdf',
                      podFilePath: '',
                      mtrFilePath: '/MTR202201/8800387484.pdf',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '1070091111',
                      customerNumber: 46030,
                      orderNumber: '01011671',
                      salesOrderId: '1141952',
                      salesOrderNumber: '01011671',
                      customerOrderNumber: '5501000288',
                      partDescription: 'VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 4,
                      actualQuantity: 4,
                      invoiceDate: '2022-01-17',
                      invoiceFilePath: '/I000045102.pdf',
                      packingListFilePath: '/CUSTOMER/PK/2021/12/PK01100173.pdf',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '3632273-01',
                      customerNumber: 45772,
                      orderNumber: '61167134',
                      salesOrderId: '1141840',
                      salesOrderNumber: '61167134',
                      customerOrderNumber: 'XARP91350',
                      partDescription: '3.000 1E0360 15.256 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 176,
                      actualQuantity: 176,
                      invoiceDate: '2022-01-17',
                      invoiceFilePath: '/I002235367.pdf',
                      packingListFilePath: '',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '9W1572-06',
                      customerNumber: 45772,
                      orderNumber: '61167135',
                      salesOrderId: '1141841',
                      salesOrderNumber: '61167135',
                      customerOrderNumber: 'TARP86554',
                      partDescription: '3.00 1E0360 28.083 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 364,
                      actualQuantity: 364,
                      invoiceDate: '2022-01-13',
                      invoiceFilePath: '/I002235366.pdf',
                      packingListFilePath: '',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '2543963-02',
                      customerNumber: 45772,
                      orderNumber: '61167096',
                      salesOrderId: '1142546',
                      salesOrderNumber: '61167096',
                      customerOrderNumber: 'TARP93946',
                      partDescription: '3.25 1E1054  9.248 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 625,
                      actualQuantity: 625,
                      invoiceDate: '2022-01-13',
                      invoiceFilePath: '/I002235997.pdf',
                      packingListFilePath: '',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '7T2033-15',
                      customerNumber: 45772,
                      orderNumber: '61167124',
                      salesOrderId: '1142148',
                      salesOrderNumber: '61167124',
                      customerOrderNumber: 'TARP86553',
                      partDescription: '4.875 1E0360 28.661 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 240,
                      actualQuantity: 240,
                      invoiceDate: '2022-01-13',
                      invoiceFilePath: '/I002235645.pdf',
                      packingListFilePath: '',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '1501307-01',
                      customerNumber: 45772,
                      orderNumber: '61167137',
                      salesOrderId: '1143632',
                      salesOrderNumber: '61167137',
                      customerOrderNumber: 'TARP90526',
                      partDescription: '4.25 1E1054  28.386 VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 96,
                      actualQuantity: 96,
                      invoiceDate: '2022-01-13',
                      invoiceFilePath: '/I002236984.pdf',
                      packingListFilePath: '',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    },
                    {
                      id: null,
                      partNumber: '8E3112-02',
                      customerNumber: 45772,
                      orderNumber: '61167094',
                      salesOrderId: '1144452',
                      salesOrderNumber: '61167094',
                      customerOrderNumber: 'TARP86563',
                      partDescription: '3.125 1E0360 22.74 +/- VAP',
                      uom: 'EA',
                      actualUom: 'EA',
                      quantity: 88,
                      actualQuantity: 88,
                      invoiceDate: '2022-01-11',
                      invoiceFilePath: '/I002237753.pdf',
                      packingListFilePath: '',
                      podFilePath: '',
                      mtrFilePath: '',
                      updatedBy: null
                    }
                  ],
                  pageable: {
                    sort: {
                      sorted: true,
                      unsorted: false,
                      empty: false
                    },
                    pageNumber: 0,
                    pageSize: 99999,
                    offset: 0,
                    paged: true,
                    unpaged: false
                  },
                  last: true,
                  totalElements: 63,
                  totalPages: 1,
                  first: true,
                  sort: {
                    sorted: true,
                    unsorted: false,
                    empty: false
                  },
                  numberOfElements: 63,
                  size: 99999,
                  number: 0,
                  empty: false
                }
              ,
              
                loaderStatus: {
                  showLoading: false
                }
              
          },
          auth: {
            authUserData: {
              id: 10,
              firstName: 'deepanshu',
              lastName: 'Tyagi',
              email: 'Deepanshu.Tyagi@compunneldigital.com',
              roles: [
                {
                  id: 1,
                  code: 'ROLE_CUSTOMER',
                 
                }
               
              ],
              status: {
                id: 1,
                code: 'A',
                description: 'Active'
              },
              type: {
                id: 1,
                code: 'I',
                description: 'Internal'
              },
              features: [],
              lastLogin: '2023-02-02T05:56:38.085+00:00',
              jobTitle: '',
              jobType: null,
              createdBy: 'System',
              createdDate: '2022-09-28T06:13:31.000+00:00',
              updatedBy: 'Deepanshu.Tyagi@compunneldigital.com',
              updatedDate: '2023-02-02T05:56:38.087+00:00',
              associateCustomerId: null
            }
          
          }
    });
    const useSelectorMock = reactRedux.useSelector;

    beforeEach(() => {
        useSelectorMock.mockImplementation((selector) =>
            selector(store?.getState())
        );

        wrapper = mount(ShallowMock(<OrderHistory />, store));
    });

    afterEach(() => {
          
        useSelectorMock.mockClear();
        wrapper.unmount();
    });

    it('render component OrderHistory', () => {
        expect(wrapper.find('OrderHistory')).toBeTruthy();
    });

    it('Email  Component ', () => {
        const button = wrapper.find('AgGridReact');
        button
          .at(0)
          .props()
          .frameworkComponents.EmailComponent({ value: 'Active' });
      });

      it('Action  Component ', () => {
        const button = wrapper.find('AgGridReact');
        button
          .at(0)
          .props()
          .frameworkComponents.ActionComponent({ data:{id:1} });
      });

      it('Handle click on custom Button', () => {
        const button = wrapper.find('ForwardRef(TextField)');
    
     
        button.at(0).props().onChange();
      });
     
   
});

